# -*- coding: utf-8 -*-
"""test_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Klj-Q55amPlAWjEBHJEkeDUZYGhGOTSU
"""

from tensorflow.keras.models import load_model

categories = ['1', '2', '3', '4', '5', '6', '7', '8', '9','10']

import numpy as np

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

model=load_model('gender_pred2.h5')

import tensorflow as tf

image = 'rachael_mcadams.jpg'

import cv2

def prepare(image):
  IMG_SIZE=64
  img_array = cv2.imread('rachael_mcadams.jpg', cv2.IMREAD_COLOR)
  new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
  return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 3)

import matplotlib.pyplot as plt

y=model.predict([prepare('rachael_mcadmas.jpg')])

print(y)

score = y[0]

# Commented out IPython magic to ensure Python compatibility.
print(
    "This is %.2f percent chance woman and %.2f man."
#     %(100*(1-score),100*score)
)